### ISSUE TITLE
div går inte att ha som bakgrund

### ISSUE THREAD

**Issue by swegoat** [SwedishArtist/Tetris#6]
@itpastorn Vi får inte diven att fylla bakgrunden i info/index.html, kan du kolla på det?

**Comment by itpastorn** [comment]
Divvarna #sky och #sea har pixlar för höjden. Byt till vh och vw.

Lägg resten i en enda div och ge den absolut position plus z-index ovanpå #art

**Comment by itpastorn** [comment]
Ett annat sätt att få en div att täcka hela ytan är:

````css
    div {
      position: absolute;
      background-color: red;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
    }
````
Men innehållet får ändå inte ha pixlar som mått!
